### GET request to example server
GET http://localhost:7070/dogs

###

GET http://localhost:7070/dogs/a

###

POST http://localhost:7070/dogs

{
    "id": 3,

    "breed": "BULLDOG"
}

###

DELETE http://localhost:7070/dogs/1

###

POST http://localhost:7070/dogs

{
    "id": 4,
    "name": "Bingo",
    "breed": "FRENCHIE"
}