### GET request to example server
GET http://localhost:7070/api/dogs

###

GET http://localhost:7070/api/dogs/2

###
POST http://localhost:7070/api/dogs

{
    "id": 3,
    "name": "Bulder",
    "breed": "BULLDOG"
}

###

DELETE http://localhost:7070/api/dogs/2

###

POST http://localhost:7070/api/dogs

{
    "id": 4,
    "name": "Bingo",
    "breed": "FRENCHIE"
}